name: Waf Python Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  waf:
    strategy:
      fail-fast: false
      matrix:
        os: [Linux]
    runs-on: [self-hosted, "${{ matrix.os }}"]
    name: ${{ matrix.os }} Waf
    env:
      python: python3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: ${{ env.python }} waf
